#!/bin/sh
#
load_viduino() {
	/bin/viduino_usb_ether_storage_init.sh
}
free_viduino() {
	/bin/viduino_usb_ether_storage_free.sh
}
case "$1" in
	start)
		load_viduino
		;;
	stop)
		free_viduino
		;;
	restart|reload)
		free_viduino
		load_viduino
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
